# Generated by Django 5.0.1 on 2024-02-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Название',
                'db_table': 'expense_Categories',
            },
        ),
        migrations.CreateModel(
            name='Goal_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('creationDate', models.DateTimeField(verbose_name='Дата создания')),
                ('completionDate', models.DateTimeField(verbose_name='Дата завершения')),
                ('additionalInformation', models.TextField(max_length=250, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Описание цели',
                'verbose_name_plural': 'Описание целей',
                'db_table': 'goal_description',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата получения')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('sourceOfIncome', models.CharField(max_length=150, verbose_name='Источник дохода')),
                ('additionalШnformation', models.CharField(max_length=150, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Доходы',
                'verbose_name_plural': 'Доходы',
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата траты')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('additionalШnformation', models.CharField(max_length=150, verbose_name='Дополнительная информация')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purpose.expense_categories', verbose_name='Категории расходов')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Financial_Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('changeInFunds', models.IntegerField(verbose_name='Изменение средств')),
                ('descriptionOfTheEvent', models.CharField(max_length=150, verbose_name='Описание события')),
                ('balanceOrResult', models.CharField(max_length=150, verbose_name='Остаток/статус выполнения')),
                ('financialInvestment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purpose.goal_description', verbose_name='Финансовые вложения')),
            ],
            options={
                'verbose_name': 'Финансовые вложения',
                'verbose_name_plural': 'Финансовых вложений',
                'db_table': 'financial_investments',
            },
        ),
    ]
