# Generated by Django 5.0.1 on 2024-03-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='Местонахождение')),
                ('mac_address', models.CharField(max_length=12, verbose_name='Mac адрес')),
                ('active', models.BooleanField(default=False, verbose_name='Используется?')),
            ],
            options={
                'verbose_name': 'Хост-устройства',
                'verbose_name_plural': 'Хост-устройства',
                'db_table': 'hostdevice',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название интерфейса')),
                ('speed', models.FloatField(verbose_name='Скорость интерфейса в Мбит/сек')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('duplex_mode', models.TextField(max_length=50, verbose_name='Режим дуплекса - полный или половинный')),
            ],
            options={
                'verbose_name': 'Интерфейс',
                'verbose_name_plural': 'Интерфейсы',
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_usage', models.CharField(max_length=150, verbose_name='Назначение')),
                ('location', models.CharField(max_length=150, verbose_name='Местонахождение')),
            ],
            options={
                'verbose_name': 'Сетевое устройство',
                'verbose_name_plural': 'Сетевые устройства',
                'db_table': 'network_device',
            },
        ),
        migrations.CreateModel(
            name='TypeDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('typeDevice', models.CharField(max_length=50, verbose_name='Тип устройства')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('about', models.CharField(blank=True, max_length=200, verbose_name='Об устройстве')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Тип устройства',
                'db_table': 'typedevice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_lastname', models.CharField(max_length=100, verbose_name='Отчество ')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='BandwidthUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('bandwidth_usage', models.FloatField(verbose_name='Использование полосы пропускания')),
                ('interfacesBandwidthUsage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.interface', verbose_name='Интерфейсы')),
            ],
            options={
                'verbose_name': 'Использование полосы пропускания',
                'verbose_name_plural': 'Использование полос пропускания',
                'db_table': 'bandwidth_usage',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной адрес?')),
                ('hostdevice_IPAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.hostdevice', verbose_name='Хост устройство')),
                ('device_IPAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'IP-адрес',
                'verbose_name_plural': 'IP-адреса',
                'db_table': 'ip_address',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='deviceInterface',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.CreateModel(
            name='DeviceTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('temperature', models.FloatField(verbose_name='Температура устройства')),
                ('deviceDeviceTemperature', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'Температура устройства',
                'verbose_name_plural': 'Температура устройства',
                'db_table': 'device_temperature',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_timestamp', models.DateTimeField(verbose_name='Время конфигурации')),
                ('configuration_details', models.TextField(verbose_name='Детали конфигурации')),
                ('deviceDeviceConfiguration', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'Конфигурация устройства',
                'verbose_name_plural': 'Конфигурации устройств',
                'db_table': 'device_configuration',
            },
        ),
        migrations.CreateModel(
            name='NetworkEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField(verbose_name='Время события')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('severity_level', models.CharField(max_length=100, verbose_name='Уровень серьезности')),
                ('deviceNetworkEvents', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'Сетевое событие',
                'verbose_name_plural': 'Сетевые события',
                'db_table': 'network_events',
            },
        ),
        migrations.CreateModel(
            name='PacketLossData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('packet_loss', models.FloatField(verbose_name='Потеря пакетов')),
                ('device_packetLossData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
                ('hostdevice_packetLossData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.hostdevice', verbose_name='Хост устройство')),
            ],
            options={
                'verbose_name': 'Потеря пакетов',
                'verbose_name_plural': 'Потеря пакетов',
                'db_table': 'packetloss_data',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('cpu_usage', models.FloatField(verbose_name='Использование ЦПУ')),
                ('memory_usage', models.FloatField(verbose_name='Использование памяти')),
                ('storage_ussage', models.FloatField(verbose_name='Использование хранилища')),
                ('devicePerformanceMetrics', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'Метрики производительности',
                'verbose_name_plural': 'Метрики производительности',
                'db_table': 'performance_metrics',
            },
        ),
        migrations.CreateModel(
            name='PowerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('power_consumption', models.FloatField(verbose_name='Потребление энергии')),
                ('devicePowerConsumption', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство')),
            ],
            options={
                'verbose_name': 'Потребление энергии',
                'verbose_name_plural': 'Потребление энергии',
                'db_table': 'рower_сonsumption',
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('inbound_traffic', models.FloatField(verbose_name='Входящий трафик')),
                ('outbound_traffic', models.FloatField(verbose_name='Исходящий трафик')),
                ('total_packets', models.FloatField(verbose_name='Общее количество пакетов')),
                ('error_packets', models.FloatField(verbose_name='Количество пакетов с ошибками')),
                ('interfacesTrafficData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.interface', verbose_name='Интерфейсы')),
            ],
            options={
                'verbose_name': 'Данные о трафике',
                'verbose_name_plural': 'Данные о трафиках',
                'db_table': 'traffic_data',
            },
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='typeNetworkDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.typedevices', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='hostdevice',
            name='typeHostDevices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.typedevices', verbose_name='Тип устройства'),
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аутентификации',
                'verbose_name_plural': 'Журналы аутентификации',
                'db_table': 'authentication_log',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Тип активности')),
                ('device_userActivity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство')),
                ('user_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TestDB.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'useractivity',
            },
        ),
    ]
