# Generated by Django 4.2.9 on 2024-02-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип устройства')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('about', models.CharField(blank=True, max_length=200, verbose_name='Об устройстве')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Тип устройства',
                'db_table': 'typedevice',
            },
        ),
        migrations.CreateModel(
            name='HostDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('MAC_address', models.CharField(max_length=12, verbose_name='МАС адрес')),
                ('packet_loss', models.FloatField(verbose_name='Потеря пакетов')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.ipaddress', verbose_name='IP адрес')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.typedevices', verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Хосты',
                'verbose_name_plural': 'Хосты',
                'db_table': 'host',
            },
        ),
    ]
