# Generated by Django 4.2.9 on 2024-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_lastname', models.CharField(max_length=100, verbose_name='Отчество ')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Тип активности')),
                ('device_userActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство')),
                ('user_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TestDB.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'db_table': 'user_activity',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDB.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аутентификации',
                'verbose_name_plural': 'Журналы аутентификации',
                'db_table': 'authentication_log',
            },
        ),
    ]
