# Generated by Django 4.2.9 on 2024-03-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetlossdata',
            name='hostdevicePacketLossData',
        ),
    ]
