# Generated by Django 4.2.9 on 2024-02-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0002_user_useractivity_authenticationlog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devicetemperature',
            table='device_temperature',
        ),
        migrations.AlterModelTable(
            name='packetlossdata',
            table='packetloss_data',
        ),
        migrations.AlterModelTable(
            name='powerconsumption',
            table='рower_сonsumption',
        ),
    ]
