# Generated by Django 5.0.1 on 2024-02-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0002_apartment_roomcount_person_apartment_room_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='apartment',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
