# Generated by Django 5.0.1 on 2024-02-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0003_remove_person_apartment_delete_apartment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomCount',
        ),
    ]
