# Generated by Django 4.2.9 on 2024-02-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0003_alter_devicetemperature_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationlog',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='device_deviceConfiguration',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='device_deviceTemperature',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='device_interface',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='device_IPAddress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='networkevents',
            name='device_networkEvents',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='packetlossdata',
            name='device_packetLossData',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='device_performanceMetrics',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='powerconsumption',
            name='device_powerConsumption',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Сетевое устройство'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='device_userActivity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDB.networkdevice', verbose_name='Устройство'),
        ),
    ]
