# Generated by Django 4.2.9 on 2024-02-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDB', '0004_alter_authenticationlog_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='type_networkDevice',
            new_name='typeNetworkDevice',
        ),
    ]
